server:
  port: 8081
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/mybatis?characterEncoding=utf-8&useSSL=false
    username: root
    password: zgx1734475W

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhg.demo.mybatisdemo.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
